"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,RefreshCw,XCircle} from "lucide-react";
import {fetchWithAuth} from "@/lib/api";

type Company={id:number;legalName:string;tradeName?:string|null;nif:string;email?:string|null;phone?:string|null;city?:string|null;province?:string|null;status:string;members:Array<{id:number;role:string;user:{name?:string|null;email?:string|null}}>};

export default function AdminB2BCompaniesPage(){
 const [status,setStatus]=useState("PENDING"),[rows,setRows]=useState<Company[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<number|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetchWithAuth(`/api/admin/b2b/companies?status=${status}`);setRows(r.data||[])}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar empresas")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[status]);
 async function change(id:number,next:string){setBusy(id);setError("");try{await fetchWithAuth("/api/admin/b2b/companies",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyId:id,status:next})});setMessage(next==="ACTIVE"?"Empresa homologada.":`Empresa atualizada para ${next}.`);await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível atualizar a empresa")}finally{setBusy(null)}}
 return <div className="space-y-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-blue-600">Admin · B2B</p><h1 className="mt-1 text-2xl font-black">Homologação de empresas</h1><p className="mt-1 text-sm text-slate-500">Valide a identidade empresarial antes de liberar condições e compras B2B.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><RefreshCw size={14} className={loading?"animate-spin":""}/>Atualizar</button></div>
  {message&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</div>}{error&&<div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}
  <div className="flex items-center gap-3"><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold"><option value="PENDING">Pendentes</option><option value="ACTIVE">Ativas</option><option value="REJECTED">Rejeitadas</option><option value="SUSPENDED">Suspensas</option><option value="ALL">Todas</option></select><span className="text-xs text-slate-500">{rows.length} empresa(s)</span></div>
  <section className="space-y-3">{rows.map(c=><article key={c.id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{c.tradeName||c.legalName}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black">{c.status}</span></div><p className="mt-2 text-xs text-slate-500">Razão social: {c.legalName} · NIF: {c.nif}</p><p className="mt-1 text-xs text-slate-500">{c.email||"Sem email"} · {c.phone||"Sem telefone"} · {[c.city,c.province].filter(Boolean).join(" · ")||"Localização não preenchida"}</p></div><div className="flex flex-wrap gap-2">{c.status!=="ACTIVE"&&<button disabled={busy===c.id} onClick={()=>void change(c.id,"ACTIVE")} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white"><CheckCircle2 size={14}/>Homologar</button>}{c.status!=="REJECTED"&&<button disabled={busy===c.id} onClick={()=>void change(c.id,"REJECTED")} className="inline-flex items-center gap-2 rounded-lg border border-rose-200 px-3 py-2 text-xs font-black text-rose-700"><XCircle size={14}/>Rejeitar</button>}{c.status==="ACTIVE"&&<button disabled={busy===c.id} onClick={()=>void change(c.id,"SUSPENDED")} className="rounded-lg border border-amber-200 px-3 py-2 text-xs font-black text-amber-700">Suspender</button>}</div></div><div className="mt-4 flex flex-wrap gap-2">{c.members.map(m=><span key={m.id} className="rounded-lg bg-slate-50 px-3 py-2 text-xs"><b>{m.user.name||m.user.email}</b> · {m.role}</span>)}</div></article>)}{!rows.length&&<div className="rounded-xl border bg-white p-10 text-center text-sm text-slate-500">Não existem empresas neste estado.</div>}</section>
 </div>
}