"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { fetchWithAuth } from "@/lib/api";
type Product={id:number;name:string;stock:number}; type Supplier={id:number;name:string;taxId?:string|null};
type Item={productId:number;quantity:number;unitCost:number}; type Purchase={id:number;purchaseNumber:string;status:string;paymentStatus:string;currency:string;total:string|number;transactionDate:string;supplier?:Supplier|null};
function money(v:string|number,c:string){return (c==="EUR"?"€ ":"Kz ")+Number(v||0).toLocaleString("pt-PT",{minimumFractionDigits:2});}
export default function PurchasesPage(){
 const [purchases,setPurchases]=useState<Purchase[]>([]);const [products,setProducts]=useState<Product[]>([]);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [currency,setCurrency]=useState<"AOA"|"EUR">("AOA");const [supplierId,setSupplierId]=useState("");const [items,setItems]=useState<Item[]>([{productId:0,quantity:1,unitCost:0}]);
 async function load(){try{const [p,s]=await Promise.all([fetchWithAuth("/api/admin/purchases"),fetchWithAuth("/api/admin/suppliers")]);setPurchases(p.data);setSuppliers(s.data||[]);}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível carregar compras.");}}
 useEffect(()=>{void load();fetchWithAuth("/api/products?page=1&pageSize=100").then(r=>setProducts(r.data||[])).catch(()=>{});},[]);
 const total=items.reduce((s,i)=>s+(Number(i.quantity)||0)*(Number(i.unitCost)||0),0);
 function update(i:number,patch:Partial<Item>){setItems(a=>a.map((x,n)=>n===i?{...x,...patch}:x));}
 async function create(){if(items.some(i=>!i.productId||i.quantity<1||i.unitCost<=0)){setMessage("Preencha corretamente os produtos da compra.");return;}setBusy(true);try{await fetchWithAuth("/api/admin/purchases",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({supplierId:supplierId?Number(supplierId):null,currency,items})});setItems([{productId:0,quantity:1,unitCost:0}]);setMessage("Compra registada como rascunho.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível registar a compra.");}finally{setBusy(false);}}
 async function action(id:number,kind:"confirm"|"cancel"){setBusy(true);try{await fetchWithAuth("/api/admin/purchases/"+id+"/"+kind,{method:"POST"});setMessage(kind==="confirm"?"Compra confirmada: despesa financeira criada e stock atualizado.":"Compra cancelada.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Operação não concluída.");}finally{setBusy(false);}}
 return <main className="min-h-screen bg-[#f7f9fc] p-4 text-gray-900 lg:p-7"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-emerald-800">Financeiro · Compras</p><h1 className="text-2xl font-black">Transações de compra</h1><p className="mt-1 text-sm text-gray-500">Registe fornecedores, custo de aquisição, entrada de stock e despesa financeira com rastreabilidade.</p></div><Link href="/admin/finance" className="text-xs font-bold text-emerald-800">← Livro financeiro</Link></div>{message&&<div className="mb-4 border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-900">{message}</div>}
 <section className="mb-6 border bg-white p-5"><h2 className="mb-4 text-sm font-black">Nova compra</h2><div className="grid gap-3 md:grid-cols-3"><label className="text-xs font-bold">Fornecedor<select value={supplierId} onChange={e=>setSupplierId(e.target.value)} className="mt-1 w-full border p-2.5"><option value="">Sem fornecedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}{s.taxId?" · "+s.taxId:""}</option>)}</select></label><label className="text-xs font-bold">Moeda<select value={currency} onChange={e=>setCurrency(e.target.value as "AOA"|"EUR")} className="mt-1 w-full border p-2.5"><option value="AOA">AOA · Kwanza</option><option value="EUR">EUR · Euro</option></select></label><div className="border bg-gray-50 p-3"><span className="text-[10px] uppercase text-gray-500">Total</span><strong className="block text-lg">{money(total,currency)}</strong></div></div>
 <div className="mt-4 space-y-2">{items.map((item,i)=><div key={i} className="grid gap-2 md:grid-cols-[1fr_130px_160px_auto]"><select value={item.productId} onChange={e=>update(i,{productId:Number(e.target.value)})} className="border p-2.5 text-xs"><option value={0}>Selecionar produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · stock {p.stock}</option>)}</select><input type="number" min="1" value={item.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})} className="border p-2.5 text-xs" placeholder="Quantidade"/><input type="number" min="0.01" step="0.01" value={item.unitCost||""} onChange={e=>update(i,{unitCost:Number(e.target.value)})} className="border p-2.5 text-xs" placeholder="Custo unitário"/><button type="button" onClick={()=>setItems(a=>a.filter((_,n)=>n!==i))} disabled={items.length===1} className="border px-3 text-xs font-bold disabled:opacity-40">Remover</button></div>)}</div>
 <div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>setItems(a=>[...a,{productId:0,quantity:1,unitCost:0}])} className="border px-3 py-2 text-xs font-bold">+ Produto</button><button type="button" disabled={busy} onClick={()=>void create()} className="bg-emerald-700 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">{busy?"A guardar...":"Registar compra"}</button></div></section>
 <section className="overflow-x-auto border bg-white"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b bg-gray-50 text-[10px] uppercase text-gray-500"><tr><th className="p-3">Compra</th><th>Fornecedor</th><th>Total</th><th>Estado</th><th>Pagamento</th><th>Data</th><th>Ações</th></tr></thead><tbody>{purchases.map(p=><tr key={p.id} className="border-b"><td className="p-3 font-bold">{p.purchaseNumber}</td><td>{p.supplier?.name||"—"}</td><td>{money(p.total,p.currency)}</td><td>{p.status}</td><td>{p.paymentStatus}</td><td>{new Date(p.transactionDate).toLocaleDateString("pt-PT")}</td><td className="space-x-2">{p.status==="DRAFT"&&<><button disabled={busy} onClick={()=>void action(p.id,"confirm")} className="font-bold text-emerald-700">Confirmar</button><button disabled={busy} onClick={()=>void action(p.id,"cancel")} className="font-bold text-red-700">Cancelar</button></>}</td></tr>)}{!purchases.length&&<tr><td colSpan={7} className="p-8 text-center text-gray-500">Nenhuma compra registada.</td></tr>}</tbody></table></section></div></main>;
}