"use client";

import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, Edit3, LoaderCircle, Search, ShieldCheck, UserCheck, UserX, X } from "lucide-react";
import { fetchWithAuth } from "@/lib/api";

type AdminUser = { id:number; name?:string|null; email?:string|null; accountName:string; accountType:string; accessRole:string; status:string; provider?:string|null; createdAt:string; lastLoginAt?:string|null; _count:{orders:number;notifications:number} };
type Stats = { total:number; admins:number; customers:number; active:number; inactive:number };

export default function AdminUsersPage() {
  const [users,setUsers]=useState<AdminUser[]>([]), [stats,setStats]=useState<Stats>({total:0,admins:0,customers:0,active:0,inactive:0});
  const [search,setSearch]=useState(""), [role,setRole]=useState("ALL"), [status,setStatus]=useState("ALL"), [page,setPage]=useState(1), [pageCount,setPageCount]=useState(1);
  const [selected,setSelected]=useState<AdminUser|null>(null), [form,setForm]=useState({name:"",email:"",status:"ACTIVE",accessRole:"CUSTOMER"});
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [notice,setNotice]=useState(""), [error,setError]=useState("");

  async function load() {
    setLoading(true); setError("");
    try {
      const query=new URLSearchParams({search,role,status,page:String(page),pageSize:"25"});
      const response=await fetchWithAuth(`/api/admin/users?${query}`);
      setUsers(response.data as AdminUser[]); setStats(response.stats as Stats); setPageCount(response.meta.pageCount||1);
    } catch (e) { setError(e instanceof Error?e.message:"Não foi possível carregar os utilizadores."); }
    finally { setLoading(false); }
  }
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),180); return()=>window.clearTimeout(timer);},[search,role,status,page]);

  function edit(user:AdminUser){setSelected(user);setForm({name:user.name||"",email:user.email||"",status:user.status,accessRole:user.accessRole});setError("");setNotice("");}
  async function save(event:FormEvent){
    event.preventDefault(); if(!selected)return; setSaving(true);setError("");setNotice("");
    try { await fetchWithAuth("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,name:form.name,email:form.email||null,status:form.status,accessRole:form.accessRole})}); setSelected(null);setNotice("Utilizador atualizado com sucesso.");await load(); }
    catch(e){setError(e instanceof Error?e.message:"Não foi possível atualizar o utilizador.");} finally{setSaving(false);}
  }

  return <main className="space-y-5">
    <div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#1555d8]">Sistema · Contas</p><h1 className="mt-1 text-2xl font-black">Utilizadores</h1><p className="mt-1 text-sm text-slate-500">Administre contas, permissões e estado de acesso sem expor credenciais.</p></div>
    {notice&&<p role="status" className="flex items-center gap-2 border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><CheckCircle2 size={16}/>{notice}</p>}
    {error&&<p role="alert" className="border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Total",stats.total,"text-slate-950"],["Administradores",stats.admins,"text-blue-700"],["Clientes",stats.customers,"text-slate-700"],["Ativos",stats.active,"text-emerald-700"],["Inativos",stats.inactive,"text-rose-700"]].map(([label,value,tone])=><div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-2 text-2xl font-black ${tone}`}>{value}</p></div>)}</div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
      <div className="grid gap-2 border-b border-slate-200 p-4 md:grid-cols-[minmax(220px,1fr)_170px_170px]"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Nome, email ou conta..." className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-blue-500 focus:bg-white"/></div><select value={role} onChange={e=>{setRole(e.target.value);setPage(1)}} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="ALL">Todos os perfis</option><option value="ADMIN">Administradores</option><option value="CUSTOMER">Clientes</option></select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="ALL">Todos os estados</option><option value="ACTIVE">Ativos</option><option value="INACTIVE">Inativos</option></select></div>
      <div className="hidden grid-cols-[1.4fr_1.4fr_0.8fr_0.7fr_0.8fr_90px] gap-3 border-b border-slate-100 bg-slate-50 px-4 py-3 text-[9px] font-black uppercase tracking-wider text-slate-500 md:grid"><span>Utilizador</span><span>Conta</span><span>Perfil</span><span>Estado</span><span>Último acesso</span><span/></div>
      {loading?<div className="flex items-center justify-center gap-2 p-12 text-sm text-slate-500"><LoaderCircle size={17} className="animate-spin"/>A carregar utilizadores...</div>:users.length===0?<div className="p-12 text-center text-sm text-slate-500">Nenhum utilizador encontrado.</div>:<div className="divide-y divide-slate-100">{users.map(user=><div key={user.id} className="grid gap-3 px-4 py-4 hover:bg-slate-50 md:grid-cols-[1.4fr_1.4fr_0.8fr_0.7fr_0.8fr_90px] md:items-center"><div className="min-w-0"><p className="truncate text-sm font-bold">{user.name||"Sem nome"}</p><p className="truncate text-xs text-slate-500">{user.email||"Sem email"}</p></div><div className="min-w-0"><p className="truncate text-xs font-semibold text-slate-700">{user.accountName}</p><p className="text-[10px] text-slate-500">{user.accountType} · {user.provider||"local"}</p></div><span className={`w-fit rounded-full px-2 py-1 text-[9px] font-bold ${user.accessRole==="ADMIN"?"bg-blue-50 text-blue-800":"bg-slate-100 text-slate-700"}`}>{user.accessRole==="ADMIN"?<><ShieldCheck size={11} className="mr-1 inline"/>Administrador</>:"Cliente"}</span><span className={`w-fit rounded-full px-2 py-1 text-[9px] font-bold ${user.status==="ACTIVE"?"bg-emerald-50 text-emerald-800":"bg-rose-50 text-rose-800"}`}>{user.status==="ACTIVE"?<UserCheck size={11} className="mr-1 inline"/>:<UserX size={11} className="mr-1 inline"/>}{user.status==="ACTIVE"?"Ativo":"Inativo"}</span><span className="text-xs text-slate-500">{user.lastLoginAt?new Date(user.lastLoginAt).toLocaleDateString("pt-PT"):"Nunca"}</span><button type="button" onClick={()=>edit(user)} className="inline-flex h-9 items-center justify-center gap-1 rounded-lg border border-slate-200 px-3 text-xs font-bold text-slate-700 hover:bg-slate-100"><Edit3 size={13}/>Editar</button></div>)}</div>}
      <div className="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-xs text-slate-500"><span>Página {page} de {pageCount}</span><div className="flex gap-2"><button disabled={page<=1||loading} onClick={()=>setPage(v=>Math.max(1,v-1))} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Anterior</button><button disabled={page>=pageCount||loading} onClick={()=>setPage(v=>Math.min(pageCount,v+1))} className="rounded-lg border border-slate-200 px-3 py-1.5 disabled:opacity-40">Seguinte</button></div></div>
    </section>
    {selected&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/45 p-4"><section role="dialog" aria-modal="true" className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><p className="text-[9px] font-black uppercase tracking-widest text-blue-700">Gestão de conta</p><h2 className="mt-1 text-lg font-black">{selected.name||selected.email||`Utilizador #${selected.id}`}</h2></div><button type="button" onClick={()=>setSelected(null)} aria-label="Fechar" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={18}/></button></div><form onSubmit={save} className="space-y-4 p-5"><label className="block text-xs font-bold text-slate-700">Nome<input value={form.name} onChange={e=>setForm(c=>({...c,name:e.target.value}))} required className="mt-1.5 h-10 w-full rounded-lg border border-slate-300 px-3 text-sm"/></label><label className="block text-xs font-bold text-slate-700">Email<input type="email" value={form.email} onChange={e=>setForm(c=>({...c,email:e.target.value}))} className="mt-1.5 h-10 w-full rounded-lg border border-slate-300 px-3 text-sm"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-700">Perfil<select value={form.accessRole} onChange={e=>setForm(c=>({...c,accessRole:e.target.value}))} className="mt-1.5 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="CUSTOMER">Cliente</option><option value="ADMIN">Administrador</option></select></label><label className="text-xs font-bold text-slate-700">Estado<select value={form.status} onChange={e=>setForm(c=>({...c,status:e.target.value}))} className="mt-1.5 h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm"><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option></select></label></div><div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" onClick={()=>setSelected(null)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-bold">Cancelar</button><button type="submit" disabled={saving} className="rounded-lg bg-[#1555d8] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving?"A guardar...":"Guardar alterações"}</button></div></form></section></div>}
  </main>;
}
