"use client";

import { FormEvent, useEffect, useState } from "react";
import { Check, CreditCard, Plus, Trash2, Smartphone } from "lucide-react";
import { fetchWithAuth } from "@/lib/api";

type PaymentMethod = { id: number; type: string; label: string; lastFour?: string; phoneNumber?: string; isDefault: boolean };
const labels: Record<string, string> = { MULTICAIXA_REFERENCE: "Referência Multicaixa", MULTICAIXA_EXPRESS: "Multicaixa Express", CARD: "Cartão bancário", TRANSFER: "Transferência bancária" };

export default function PaymentMethodsPage() {
  const [methods, setMethods] = useState<PaymentMethod[]>([]); const [open, setOpen] = useState(false); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ type: "MULTICAIXA_EXPRESS", label: "", lastFour: "", phoneNumber: "", isDefault: false });
  function load() { fetchWithAuth("/api/account/payment-methods").then((response) => setMethods(response.data)).catch(() => setMessage("Não foi possível carregar os métodos de pagamento.")); }
  useEffect(load, []);
  async function submit(event: FormEvent) { event.preventDefault(); try { await fetchWithAuth("/api/account/payment-methods", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, lastFour: form.lastFour || undefined, phoneNumber: form.phoneNumber || undefined }) }); setOpen(false); setForm({ type: "MULTICAIXA_EXPRESS", label: "", lastFour: "", phoneNumber: "", isDefault: false }); load(); } catch { setMessage("Não foi possível guardar o método."); } }
  async function remove(id: number) { try { await fetchWithAuth(`/api/account/payment-methods/${id}`, { method: "DELETE" }); load(); } catch { setMessage("Não foi possível remover o método."); } }
  async function makeDefault(id: number) { try { await fetchWithAuth(`/api/account/payment-methods/${id}/default`, { method: "POST" }); load(); } catch { setMessage("Não foi possível definir o método principal."); } }
  return <div className="space-y-6"><header className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#1d6ac4]">Conta</p><h1 className="mt-2 text-2xl font-bold text-gray-900">Métodos de pagamento</h1><p className="mt-1 text-sm text-gray-500">Guarde apenas referências seguras para tornar o checkout mais rápido.</p></div><button onClick={() => setOpen(true)} className="btn-primary"><Plus size={16} /> Adicionar método</button></header>{message && <p role="status" className="rounded-lg bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</p>}
    {open && <form onSubmit={submit} className="card grid gap-4 p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 text-lg font-bold text-gray-900">Adicionar método</h2><label><span className="mb-1 block text-xs font-bold text-gray-700">Tipo</span><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"><option value="MULTICAIXA_EXPRESS">Multicaixa Express</option><option value="MULTICAIXA_REFERENCE">Referência Multicaixa</option><option value="CARD">Cartão bancário</option><option value="TRANSFER">Transferência bancária</option></select></label><label><span className="mb-1 block text-xs font-bold text-gray-700">Nome</span><input required value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} placeholder="Ex.: Meu Multicaixa" className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm" /></label>{form.type === "CARD" && <label><span className="mb-1 block text-xs font-bold text-gray-700">Últimos 4 dígitos</span><input required pattern="[0-9]{4}" value={form.lastFour} onChange={(event) => setForm({ ...form, lastFour: event.target.value })} maxLength={4} className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm" /></label>}{form.type === "MULTICAIXA_EXPRESS" && <label><span className="mb-1 block text-xs font-bold text-gray-700">Número de telefone</span><input required value={form.phoneNumber} onChange={(event) => setForm({ ...form, phoneNumber: event.target.value })} placeholder="+244 900 000 000" className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm" /></label>}<label className="flex items-center gap-2 text-sm font-semibold text-gray-700"><input type="checkbox" checked={form.isDefault} onChange={(event) => setForm({ ...form, isDefault: event.target.checked })} /> Definir como principal</label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setOpen(false)} className="btn-secondary">Cancelar</button><button className="btn-primary">Guardar</button></div></form>}
    <div className="space-y-3">{methods.map((method) => <article key={method.id} className="card flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-50 text-[#1d6ac4]">{method.type === "MULTICAIXA_EXPRESS" ? <Smartphone size={19} /> : <CreditCard size={19} />}</span><div><h2 className="font-bold text-gray-900">{method.label}</h2><p className="mt-1 text-xs text-gray-500">{labels[method.type]}{method.lastFour ? ` terminado em ${method.lastFour}` : method.phoneNumber ? ` · ${method.phoneNumber}` : ""}</p>{method.isDefault && <span className="mt-2 inline-flex items-center gap-1 text-[10px] font-bold text-emerald-700"><Check size={12} /> Principal</span>}</div></div><div className="flex items-center gap-3"><button aria-label="Remover método" title="Remover método" onClick={() => remove(method.id)} className="text-gray-500 hover:text-red-600"><Trash2 size={16} /></button>{!method.isDefault && <button onClick={() => makeDefault(method.id)} className="text-xs font-bold text-[#1d6ac4]">Tornar principal</button>}</div></article>)}</div>{!methods.length && !open && <div className="card p-10 text-center text-sm text-gray-500">Ainda não tem métodos de pagamento guardados.</div>}</div>;
}