"use client";
import { FormEvent, useEffect, useState } from "react";
import { Check, Copy, KeyRound, Laptop, LockKeyhole, LogOut, RefreshCw, ShieldCheck, Smartphone, XCircle } from "lucide-react";
import { fetchWithAuth } from "@/lib/api";
type Session={id:number;deviceName:string;browser:string;operatingSystem:string;ipAddress?:string|null;createdAt:string;lastActivityAt:string;expiresAt:string};
type Event={id:number;type:string;status:string;ipAddress?:string|null;createdAt:string};
const labels:Record<string,string>={LOGIN_SUCCESS:"Login bem-sucedido",LOGIN_SUCCESS_2FA:"Login com 2FA",REGISTER:"Conta criada",TWO_FACTOR_ENABLED:"2FA ativado",TWO_FACTOR_DISABLED:"2FA desativado",SESSION_REVOKED:"Sessão terminada",ALL_SESSIONS_REVOKED:"Todas as sessões terminadas",TWO_FACTOR_FAILED:"Falha no 2FA"};
export default function SecurityPanel(){
 const [enabled,setEnabled]=useState(false); const [sessions,setSessions]=useState<Session[]>([]); const [events,setEvents]=useState<Event[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 const [secret,setSecret]=useState(""); const [otpauth,setOtpauth]=useState(""); const [code,setCode]=useState(""); const [recovery,setRecovery]=useState<string[]>([]);
 const [currentPassword,setCurrentPassword]=useState(""); const [newPassword,setNewPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState("");
 async function load(){setLoading(true);try{const r=await fetchWithAuth("/api/auth/security");setEnabled(r.data.twoFactorEnabled);setSessions(r.data.sessions);setEvents(r.data.events);}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível carregar a segurança.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function securityAction(action:string,extra:Record<string,unknown>={}){setBusy(true);setMessage("");try{const r=await fetchWithAuth("/api/auth/security",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...extra})});return r.data;}catch(e){setMessage(e instanceof Error?e.message:"Operação não concluída.");return null;}finally{setBusy(false);}}
 async function begin2fa(){const data=await securityAction("begin-2fa");if(data){setSecret(data.secret);setOtpauth(data.otpauth);setCode("");}}
 async function verify2fa(){const data=await securityAction("verify-2fa",{code});if(data){setEnabled(true);setRecovery(data.recoveryCodes||[]);setSecret("");setOtpauth("");setCode("");await load();}}
 async function disable2fa(){const value=window.prompt("Introduza o código de 6 dígitos do autenticador para desativar o 2FA.");if(value) {const data=await securityAction("disable-2fa",{code:value});if(data){setEnabled(false);await load();}}}
 async function revoke(id:number){const data=await securityAction("revoke-session",{sessionId:id});if(data)await load();}
 async function revokeAll(){if(!window.confirm("Terminar todas as outras sessões?"))return;const data=await securityAction("revoke-all");if(data)await load();}
 async function changePassword(e:FormEvent){e.preventDefault();if(newPassword!==confirmPassword){setMessage("As palavras-passe não coincidem.");return;}setBusy(true);try{await fetchWithAuth("/api/auth/password",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});setCurrentPassword("");setNewPassword("");setConfirmPassword("");setMessage("Palavra-passe alterada com sucesso.");}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível alterar a palavra-passe.");}finally{setBusy(false);}}
 const score=enabled?100:65;
 return <div className="space-y-6">
  <div className="rounded-2xl border border-gray-200 bg-gradient-to-br from-blue-50 to-white p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-[#1d6ac4]">Centro de segurança</p><h2 className="mt-1 text-xl font-black text-gray-900">Proteja a sua conta</h2><p className="mt-1 text-sm text-gray-500">Controle palavras-passe, autenticação e dispositivos com acesso.</p></div><div className="text-right"><div className="text-3xl font-black text-gray-900">{score}<span className="text-sm text-gray-400">/100</span></div><p className="text-xs font-bold text-green-700">{enabled?"Proteção forte":"Proteção recomendada"}</p></div></div></div>
  {message&&<div role="status" className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}
  {recovery.length>0&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-start gap-3"><ShieldCheck className="text-amber-600"/><div className="flex-1"><h3 className="font-black text-gray-900">Códigos de recuperação</h3><p className="mt-1 text-xs text-gray-600">Guarde estes códigos num local seguro. Cada código só pode ser usado uma vez.</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{recovery.map(x=><code key={x} className="rounded-lg bg-white px-2 py-2 text-center text-xs font-bold">{x}</code>)}</div><button type="button" onClick={()=>navigator.clipboard?.writeText(recovery.join("\\n"))} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-[#1d6ac4]"><Copy size={14}/>Copiar códigos</button></div><button type="button" onClick={()=>setRecovery([])}><XCircle size={18} className="text-gray-400"/></button></div></div>}
  <section className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-start gap-3"><ShieldCheck className={enabled?"text-green-600":"text-gray-400"}/><div><h3 className="font-black text-gray-900">Autenticação em dois factores</h3><p className="mt-1 text-sm text-gray-500">{enabled?"Ativa — novos logins exigem um código do autenticador.":"Desativada — recomendamos ativá-la para proteger a conta."}</p></div></div>{enabled?<button type="button" disabled={busy} onClick={disable2fa} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-black text-red-600">Desativar 2FA</button>:<button type="button" disabled={busy} onClick={begin2fa} className="rounded-lg bg-[#1d6ac4] px-3 py-2 text-xs font-black text-white">Ativar 2FA</button>}</div>
   {secret&&<div className="mt-5 rounded-xl bg-gray-50 p-4"><p className="text-xs font-bold text-gray-600">Chave secreta (adicione manualmente no seu Authenticator)</p><code className="mt-2 block break-all rounded-lg bg-white p-3 text-sm font-black">{secret}</code><p className="mt-3 text-xs text-gray-500">URI TOTP: <span className="break-all">{otpauth}</span></p><div className="mt-4 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value)} maxLength={6} inputMode="numeric" placeholder="000000" className="settings-input max-w-[150px] text-center tracking-[0.3em]"/><button type="button" disabled={busy||code.length!==6} onClick={verify2fa} className="rounded-lg bg-[#1d6ac4] px-4 py-2 text-xs font-black text-white">Verificar</button></div></div>}</section>
  <section className="rounded-2xl border border-gray-200 bg-white p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><h3 className="font-black text-gray-900">Palavra-passe</h3><p className="text-sm text-gray-500">Use uma palavra-passe longa e exclusiva.</p></div><KeyRound className="text-[#1d6ac4]"/></div><form onSubmit={changePassword} className="grid gap-4 sm:grid-cols-3"><input type="password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="Atual" className="settings-input"/><input type="password" required minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="Nova (mín. 12)" className="settings-input"/><input type="password" required minLength={12} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Confirmar" className="settings-input"/><div className="sm:col-span-3"><button disabled={busy} className="btn-primary"><LockKeyhole size={15}/>{busy?"A guardar...":"Alterar palavra-passe"}</button></div></form></section>
  <section className="rounded-2xl border border-gray-200 bg-white p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black text-gray-900">Dispositivos activos</h3><p className="text-sm text-gray-500">Revogue acessos que já não reconhece.</p></div><button type="button" disabled={busy} onClick={revokeAll} className="inline-flex items-center gap-2 rounded-lg border border-gray-200 px-3 py-2 text-xs font-black text-gray-700"><LogOut size={14}/>Terminar outras sessões</button></div>{loading?<p className="text-sm text-gray-500">A carregar...</p>:sessions.length===0?<p className="text-sm text-gray-500">Nenhuma sessão persistente encontrada.</p>:<div className="divide-y divide-gray-100">{sessions.map((s,i)=><div key={s.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div className="flex items-center gap-3">{s.deviceName.toLowerCase().includes("android")||s.deviceName.toLowerCase().includes("iphone")?<Smartphone className="text-[#1d6ac4]"/>:<Laptop className="text-[#1d6ac4]"/>}<div><p className="text-sm font-black text-gray-900">{s.browser} · {s.operatingSystem}{i===0&&<span className="ml-2 rounded-full bg-green-100 px-2 py-0.5 text-[9px] text-green-700">Mais recente</span>}</p><p className="text-xs text-gray-500">{s.ipAddress||"IP indisponível"} · Última atividade {new Date(s.lastActivityAt).toLocaleString("pt-PT")}</p></div></div><button type="button" disabled={busy} onClick={()=>revoke(s.id)} className="text-xs font-black text-red-600">Terminar</button></div>)}</div>}</section>
  <section className="rounded-2xl border border-gray-200 bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-black text-gray-900">Sessões recentes</h3><p className="text-sm text-gray-500">Histórico das principais operações de segurança.</p></div><RefreshCw size={18} className="text-gray-400"/></div><div className="divide-y divide-gray-100">{events.map(e=><div key={e.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-semibold text-gray-800">{labels[e.type]||e.type}</p><p className="text-xs text-gray-500">{e.ipAddress||"IP indisponível"} · {new Date(e.createdAt).toLocaleString("pt-PT")}</p></div><span className="text-[10px] font-black text-green-700">{e.status}</span></div>)}</div></section>
 </div>;
}