import { authenticate, errorResponse, readJson, userSubject } from "@/lib/server/api";
import { prisma } from "@/lib/server/prisma";
import { z } from "zod";
export const runtime="nodejs";
const schema=z.object({legalName:z.string().trim().min(2).max(160),tradeName:z.string().trim().max(160).optional().nullable(),nif:z.string().trim().min(5).max(40),email:z.string().email().nullable().optional(),phone:z.string().trim().max(40).optional().nullable(),country:z.enum(["Angola","Portugal"]).default("Angola"),province:z.string().trim().max(80).optional().nullable(),city:z.string().trim().max(80).optional().nullable(),address:z.string().trim().max(240).optional().nullable()});
async function getUser(request:Request){const auth=await authenticate(request);const sub=userSubject(auth);if(!sub)return null;return prisma.user.findUnique({where:{externalId:sub},select:{id:true,accountType:true}});}
export async function GET(request:Request){const user=await getUser(request);if(!user)return errorResponse("Não autenticado.",401);const member=await prisma.companyMember.findFirst({where:{userId:user.id,status:"ACTIVE"},include:{company:true}});if(!member)return Response.json({data:null});return Response.json({data:member.company,role:member.role});}
export async function POST(request:Request){const user=await getUser(request);if(!user)return errorResponse("Não autenticado.",401);if(user.accountType!=="B2B")return errorResponse("Esta operação requer uma conta empresarial.",403);const body=await readJson(request);const parsed=schema.safeParse(body);if(!parsed.success)return errorResponse("Dados empresariais inválidos.",400);try{const company=await prisma.$transaction(async tx=>{const existing=await tx.company.findUnique({where:{nif:parsed.data.nif}});if(existing)throw new Error("NIF_ALREADY_EXISTS");const c=await tx.company.create({data:{...parsed.data,status:"PENDING"}});await tx.companyMember.create({data:{companyId:c.id,userId:user.id,role:"OWNER"}});await tx.user.update({where:{id:user.id},data:{companyId:c.id}});return c;});return Response.json({data:company},{status:201});}catch(e){if(e instanceof Error&&e.message==="NIF_ALREADY_EXISTS")return errorResponse("Já existe uma empresa com este NIF.",409);return errorResponse("Não foi possível criar a empresa.",500);}}
export async function PATCH(request:Request){const user=await getUser(request);if(!user)return errorResponse("Não autenticado.",401);const member=await prisma.companyMember.findFirst({where:{userId:user.id,status:"ACTIVE",role:"OWNER"},include:{company:true}});if(!member)return errorResponse("Sem permissão para alterar a empresa.",403);const parsed=schema.partial().safeParse(await readJson(request));if(!parsed.success)return errorResponse("Dados inválidos.",400);const data=parsed.data;if(data.nif && data.nif!==member.company.nif)return errorResponse("O NIF não pode ser alterado pelo perfil empresarial. Contacte a equipa de validação.",409);const countryChanged=Boolean(data.country && data.country!==member.company.country);const company=await prisma.company.update({where:{id:member.companyId},data:{...data,...(countryChanged?{status:"PENDING"}:{})}});return Response.json({data:company,revalidationRequired:countryChanged});}
