-- Promotion & omnichannel pricing engine
ALTER TABLE "Order" ADD COLUMN "discountTotalEUR" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "discountTotalKZ" DECIMAL(12,2) NOT NULL DEFAULT 0;
CREATE TABLE "Promotion" ("id" SERIAL NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"description" TEXT,"code" TEXT,"status" TEXT NOT NULL DEFAULT 'DRAFT',"startAt" TIMESTAMP(3) NOT NULL,"endAt" TIMESTAMP(3),"priority" INTEGER NOT NULL DEFAULT 0,"stackable" BOOLEAN NOT NULL DEFAULT false,"exclusive" BOOLEAN NOT NULL DEFAULT false,"usageLimit" INTEGER,"perCustomerLimit" INTEGER,"minOrderAOA" DECIMAL(12,2),"minOrderEUR" DECIMAL(10,2),"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Promotion_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Promotion_slug_key" ON "Promotion"("slug");
CREATE UNIQUE INDEX "Promotion_code_key" ON "Promotion"("code");
CREATE INDEX "Promotion_status_active_startAt_endAt_idx" ON "Promotion"("status","active","startAt","endAt");
CREATE INDEX "Promotion_priority_idx" ON "Promotion"("priority");
CREATE TABLE "PromotionRule" ("id" SERIAL NOT NULL,"promotionId" INTEGER NOT NULL,"kind" TEXT NOT NULL,"operator" TEXT NOT NULL DEFAULT 'EQ',"value" TEXT NOT NULL,CONSTRAINT "PromotionRule_pkey" PRIMARY KEY ("id"));
CREATE INDEX "PromotionRule_promotionId_kind_idx" ON "PromotionRule"("promotionId","kind");
CREATE TABLE "PromotionAction" ("id" SERIAL NOT NULL,"promotionId" INTEGER NOT NULL,"type" TEXT NOT NULL,"value" DECIMAL(12,2),"maxDiscount" DECIMAL(12,2),CONSTRAINT "PromotionAction_pkey" PRIMARY KEY ("id"));
CREATE INDEX "PromotionAction_promotionId_idx" ON "PromotionAction"("promotionId");
CREATE TABLE "PromotionProduct" ("promotionId" INTEGER NOT NULL,"productId" INTEGER NOT NULL,CONSTRAINT "PromotionProduct_pkey" PRIMARY KEY ("promotionId","productId"));
CREATE INDEX "PromotionProduct_productId_idx" ON "PromotionProduct"("productId");
CREATE TABLE "PromotionCategory" ("promotionId" INTEGER NOT NULL,"categoryId" INTEGER NOT NULL,CONSTRAINT "PromotionCategory_pkey" PRIMARY KEY ("promotionId","categoryId"));
CREATE INDEX "PromotionCategory_categoryId_idx" ON "PromotionCategory"("categoryId");
CREATE TABLE "PromotionBrand" ("promotionId" INTEGER NOT NULL,"brandId" INTEGER NOT NULL,CONSTRAINT "PromotionBrand_pkey" PRIMARY KEY ("promotionId","brandId"));
CREATE INDEX "PromotionBrand_brandId_idx" ON "PromotionBrand"("brandId");
CREATE TABLE "PromotionUsage" ("id" SERIAL NOT NULL,"promotionId" INTEGER NOT NULL,"userId" INTEGER NOT NULL,"orderId" INTEGER NOT NULL,"couponCode" TEXT,"discountAmount" DECIMAL(12,2) NOT NULL,"currency" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromotionUsage_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PromotionUsage_promotionId_orderId_key" ON "PromotionUsage"("promotionId","orderId");
CREATE INDEX "PromotionUsage_promotionId_userId_idx" ON "PromotionUsage"("promotionId","userId");
CREATE TABLE "OrderDiscount" ("id" SERIAL NOT NULL,"orderId" INTEGER NOT NULL,"promotionId" INTEGER,"promotionName" TEXT NOT NULL,"code" TEXT,"type" TEXT NOT NULL,"amount" DECIMAL(12,2) NOT NULL,"currency" TEXT NOT NULL,"metadata" JSONB,CONSTRAINT "OrderDiscount_pkey" PRIMARY KEY ("id"));
CREATE INDEX "OrderDiscount_orderId_idx" ON "OrderDiscount"("orderId");
CREATE INDEX "OrderDiscount_promotionId_idx" ON "OrderDiscount"("promotionId");
ALTER TABLE "PromotionRule" ADD CONSTRAINT "PromotionRule_promotionId_fkey" FOREIGN KEY ("promotionId") REFERENCES "Promotion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromotionAction" ADD CONSTRAINT "PromotionAction_promotionId_fkey" FOREIGN KEY ("promotionId") REFERENCES "Promotion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromotionProduct" ADD CONSTRAINT "PromotionProduct_promotionId_fkey" FOREIGN KEY ("promotionId") REFERENCES "Promotion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromotionProduct" ADD CONSTRAINT "PromotionProduct_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromotionCategory" ADD CONSTRAINT "PromotionCategory_promotionId_fkey" FOREIGN KEY ("promotionId") REFERENCES "Promotion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromotionCategory" ADD CONSTRAINT "PromotionCategory_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromotionBrand" ADD CONSTRAINT "PromotionBrand_promotionId_fkey" FOREIGN KEY ("promotionId") REFERENCES "Promotion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromotionBrand" ADD CONSTRAINT "PromotionBrand_brandId_fkey" FOREIGN KEY ("brandId") REFERENCES "Brand"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromotionUsage" ADD CONSTRAINT "PromotionUsage_promotionId_fkey" FOREIGN KEY ("promotionId") REFERENCES "Promotion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PromotionUsage" ADD CONSTRAINT "PromotionUsage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PromotionUsage" ADD CONSTRAINT "PromotionUsage_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderDiscount" ADD CONSTRAINT "OrderDiscount_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderDiscount" ADD CONSTRAINT "OrderDiscount_promotionId_fkey" FOREIGN KEY ("promotionId") REFERENCES "Promotion"("id") ON DELETE SET NULL ON UPDATE CASCADE;