import Link from "next/link";
import { ArrowRight, CheckCircle2, CreditCard, Headphones, LockKeyhole, MapPin, PackageCheck, ShieldCheck, Truck } from "lucide-react";

const pages: Record<string,{kicker:string;title:string;intro:string;sections:{title:string;body:string}[];cta?:{label:string;href:string}}> = {
about:{kicker:"RUBRICA DILIGENTE · EMPRESA",title:"Tecnologia para avançar.",intro:"Uma experiência de comércio eletrónico pensada para clientes em Angola e Portugal, com catálogo centralizado, compra segura e apoio especializado.",sections:[{title:"O que fazemos",body:"Disponibilizamos equipamentos, computadores, smartphones, acessórios e outras soluções tecnológicas através de uma experiência digital simples e orientada para a compra."},{title:"Dois mercados, uma experiência",body:"A loja foi preparada para Angola e Portugal, com moeda e contexto de mercado selecionáveis."},{title:"Particulares e empresas",body:"Clientes finais podem comprar normalmente e empresas podem utilizar a área B2B para cotações e compras por volume."}],cta:{label:"Explorar catálogo",href:"/products"}},
contact:{kicker:"CONTACTOS",title:"Fale connosco.",intro:"Tem uma dúvida sobre um produto, uma encomenda ou uma condição comercial? Encontre aqui o próximo passo.",sections:[{title:"Apoio comercial",body:"Para dúvidas sobre produtos, preços e disponibilidade, utilize o nosso suporte."},{title:"Localização",body:"4425-440 Mala, Portugal."},{title:"Telefone",body:"+33 7 58 92 00 80."}],cta:{label:"Entrar na conta",href:"/login"}},
support:{kicker:"CENTRO DE AJUDA",title:"Estamos aqui para ajudar.",intro:"Resolva dúvidas de compra, entrega, pagamento e pós-venda sem sair da experiência da loja.",sections:[{title:"Antes da compra",body:"Use o catálogo, pesquisa, categorias e comparação para encontrar o produto adequado."},{title:"Encomendas",body:"Depois de iniciar sessão, consulte o histórico e estado das suas encomendas."},{title:"Pagamento",body:"Os métodos disponíveis são apresentados no checkout de acordo com o mercado e configuração."},{title:"Precisa de apoio?",body:"Contacte-nos com o número da encomenda e uma descrição objetiva do pedido."}],cta:{label:"Contactar-nos",href:"/info/contact"}},
"how-to-buy":{kicker:"COMO COMPRAR",title:"Comprar deve ser simples.",intro:"Do primeiro clique à confirmação da encomenda, reduzimos os passos desnecessários.",sections:[{title:"1. Encontre",body:"Pesquise, filtre ou navegue pelas categorias."},{title:"2. Confirme",body:"Consulte preço, stock, especificações, entrega e condições."},{title:"3. Carrinho",body:"Escolha a quantidade e adicione o produto ao carrinho."},{title:"4. Checkout",body:"Confirme entrega e pagamento e conclua a encomenda."}],cta:{label:"Começar a comprar",href:"/products"}},
payments:{kicker:"PAGAMENTOS",title:"Pagamento com contexto claro.",intro:"Os métodos disponíveis dependem do mercado e das condições da encomenda.",sections:[{title:"Angola",body:"Podem estar disponíveis opções locais como MULTICAIXA, conforme a configuração ativa."},{title:"Portugal",body:"Podem estar disponíveis cartão, MB WAY e outras opções configuradas."},{title:"Segurança",body:"Os dados de pagamento são processados pelos provedores integrados à plataforma."}],cta:{label:"Ver produtos",href:"/products"}},
shipping:{kicker:"ENTREGAS",title:"Escolha como quer receber.",intro:"A disponibilidade e o custo dependem do mercado, peso, método e morada.",sections:[{title:"Angola",body:"As modalidades disponíveis são apresentadas no checkout conforme a cobertura configurada."},{title:"Portugal",body:"O checkout apresenta as opções e custos aplicáveis antes da confirmação."},{title:"Confirmação",body:"O custo de entrega é apresentado antes de criar a encomenda."}],cta:{label:"Ir para o catálogo",href:"/products"}},
returns:{kicker:"TROCAS E DEVOLUÇÕES",title:"Compra com regras claras.",intro:"Em caso de problema, o suporte orienta o cliente de acordo com as condições aplicáveis.",sections:[{title:"Pedido",body:"Contacte o suporte com o número da encomenda e uma descrição do caso."},{title:"Avaliação",body:"O pedido é analisado de acordo com o estado do artigo e condições da compra."},{title:"Resolução",body:"Quando aplicável, serão fornecidas instruções para devolução ou resolução."}],cta:{label:"Contactar suporte",href:"/info/support"}},
warranty:{kicker:"GARANTIA E PÓS-VENDA",title:"Suporte depois da compra.",intro:"A experiência não termina quando a encomenda é entregue.",sections:[{title:"Garantia",body:"As condições variam conforme o produto e documentação associada."},{title:"Assistência",body:"Tenha consigo o número da encomenda e uma descrição do problema."},{title:"Acompanhamento",body:"A sua conta mantém o histórico necessário para facilitar o atendimento."}],cta:{label:"Aceder à conta",href:"/login"}},
terms:{kicker:"DOCUMENTAÇÃO",title:"Termos e condições.",intro:"Consulte as regras gerais da experiência de compra. A versão jurídica deve refletir os termos aprovados pela empresa.",sections:[{title:"Compras",body:"O cliente confirma os dados apresentados no checkout antes de concluir a encomenda."},{title:"Preços e disponibilidade",body:"Preços, stock e condições podem variar e devem ser confirmados no momento da compra."},{title:"Conta",body:"O cliente deve manter as credenciais seguras e os dados corretos."}],cta:{label:"Voltar à loja",href:"/"}},
privacy:{kicker:"PRIVACIDADE",title:"A sua informação merece cuidado.",intro:"A política definitiva deve refletir os processos reais da empresa e a legislação aplicável.",sections:[{title:"Dados da conta",body:"Podem ser tratados dados necessários para autenticação, encomendas, entrega e suporte."},{title:"Pagamentos",body:"Os dados sensíveis de pagamento são tratados pelos provedores configurados."},{title:"Direitos",body:"Pedidos relacionados com os seus dados devem ser encaminhados pelos canais oficiais."}],cta:{label:"Contactar a empresa",href:"/info/contact"}},
blog:{kicker:"RUBRICA DILIGENTE",title:"Conteúdos e novidades.",intro:"Guias de compra, novidades tecnológicas, comparativos e informação útil.",sections:[{title:"Guias de compra",body:"Conteúdos para ajudar a escolher equipamentos."},{title:"Novidades",body:"Lançamentos e atualizações relevantes do catálogo."},{title:"Comparação",body:"Compare produtos lado a lado antes de comprar."}],cta:{label:"Comparar produtos",href:"/compare"}}
};
const icons=[ShieldCheck,Truck,PackageCheck,CreditCard,Headphones,LockKeyhole,CheckCircle2,MapPin];
export default async function PublicInfoPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug]??pages.support;return <main className="min-h-screen bg-[#f7f9fc] text-gray-900"><div className="border-b bg-white"><div className="container mx-auto px-4 py-3 text-xs text-gray-500"><Link href="/" className="hover:text-[#1d6ac4]">Início</Link><span className="mx-2">›</span>{page.title}</div></div><section className="relative overflow-hidden bg-[#0c1b2a]"><div className="container mx-auto px-4 py-16 sm:py-20"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[#f6b73c]">{page.kicker}</p><h1 className="mt-3 text-4xl font-black tracking-tight text-white sm:text-5xl">{page.title}</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-blue-100 sm:text-base">{page.intro}</p>{page.cta&&<Link href={page.cta.href} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#f6b73c] px-5 py-3 text-sm font-black text-[#132238]">{page.cta.label}<ArrowRight size={17}/></Link>}</div></section><section className="container mx-auto grid gap-4 px-4 py-10 sm:grid-cols-2 lg:grid-cols-3">{page.sections.map((s,i)=>{const Icon=icons[i%icons.length];return <article key={s.title} className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#e8f0fc] text-[#1d6ac4]"><Icon size={18}/></span><h2 className="mt-4 text-base font-black">{s.title}</h2><p className="mt-2 text-sm leading-6 text-gray-600">{s.body}</p></article>})}</section></main>}