"use client";

import { FormEvent, useEffect, useState } from "react";
import { Check, Copy, Tag } from "lucide-react";
import { fetchWithAuth } from "@/lib/api";

type Coupon = { id: number; code: string; description: string; discountType: string; discountValue: string; minimumOrderKZ?: string; expiresAt?: string; usedAt?: string };
export default function CouponsPage() {
  const [coupons, setCoupons] = useState<Coupon[]>([]); const [code, setCode] = useState(""); const [message, setMessage] = useState("");
  function load() { fetchWithAuth("/api/account/coupons").then((response) => setCoupons(response.data)).catch(() => setMessage("Não foi possível carregar os cupões.")); }
  useEffect(load, []);
  async function claim(event: FormEvent) { event.preventDefault(); setMessage(""); try { await fetchWithAuth("/api/account/coupons/claim", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }); setCode(""); setMessage("Cupão adicionado à sua conta."); load(); } catch { setMessage("Cupão inválido, expirado ou já adicionado."); } }
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#1d6ac4]">Conta</p><h1 className="mt-2 text-2xl font-bold text-gray-900">Os meus cupões</h1><p className="mt-1 text-sm text-gray-500">Consulte os seus benefícios e adicione novos códigos promocionais.</p></header><form onSubmit={claim} className="card flex flex-col gap-3 p-5 sm:flex-row"><input required value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="Introduza o código do cupão" className="min-w-0 flex-1 rounded-lg border border-gray-300 px-3 py-2.5 text-sm uppercase outline-none focus:border-[#1d6ac4]" /><button className="btn-primary">Adicionar cupão</button></form>{message && <p role="status" className="rounded-lg bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</p>}<div className="grid gap-4 md:grid-cols-2">{coupons.map((coupon) => <article key={coupon.id} className="card border-l-4 border-l-[#1d6ac4] p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-50 text-[#1d6ac4]"><Tag size={19} /></span><div><p className="text-lg font-black text-gray-900">{coupon.discountType === "PERCENTAGE" ? `${coupon.discountValue}%` : `Kz ${Number(coupon.discountValue).toLocaleString("pt-AO")}`}</p><p className="text-sm text-gray-600">{coupon.description}</p></div></div><button aria-label="Copiar cupão" title="Copiar cupão" onClick={() => navigator.clipboard?.writeText(coupon.code)} className="text-gray-500 hover:text-[#1d6ac4]"><Copy size={16} /></button></div><div className="mt-4 flex items-center justify-between border-t border-gray-100 pt-3 text-xs"><strong className="tracking-widest text-[#1d6ac4]">{coupon.code}</strong><span className={coupon.usedAt ? "text-gray-400" : "font-bold text-emerald-700"}>{coupon.usedAt ? "Utilizado" : <><Check size={12} className="mr-1 inline" />Disponível</>}</span></div>{coupon.minimumOrderKZ && <p className="mt-2 text-[10px] text-gray-500">Valor mínimo: Kz {Number(coupon.minimumOrderKZ).toLocaleString("pt-AO")}</p>}</article>)}</div>{!coupons.length && <div className="card p-10 text-center text-sm text-gray-500">Ainda não tem cupões. Introduza um código acima para o adicionar.</div>}</div>;
}